### PR TITLE
swap vector type with generic list symbols

### PR DESCRIPTION
**Pull request by nmarley**
Trying to make this as generic and non-C++-specific as possible. I'd like to wait 'til #26 is merged and I will rebase to resolve conflicts.

### CODE REVIEW

**Comment by UdjinM6** [comment]
But this reason doesn't work for dip4 actually...

**Comment by nmarley** [comment]
@UdjinM6 I think we need to change DIP4 to add the counts, same as @antouhou did for another one of the DIPs, right?

**Comment by UdjinM6** [comment]
I guess so. If you want to transition from `vector` to `[]` you need `payloadSigSize | compactSize uint | 1-9 ` to make sure serialization matches.

**Comment by nmarley** [comment]
Well I think it would be more explicit regardless -- I would not have expected `vector` to have a compactSize pre-pended by default, I would expect this to be very explicit, just like Bitcoin TXes have this field (e.g. for number of number of TXes, TX inputs, outputs).

Will rebase now that #26 is merged and add these fields if necessary.

**Comment by nmarley** [comment]
Could we merge this and follow up w/#29? (So I'm not changing format and adding fields in same PR)?

**Comment by thephez** [comment]
Merging the BLS PR caused a conflict 🙁

**Comment by nmarley** [comment]
Rebased & force pushed (both this and #29)

**Pull request merged**
