### PR TITLE
DIP14: add serialization test vectors

### PR DESCRIPTION
**Pull request by dashameter**
Add serialization test vectors to DIP14 for xprivkey and xpubkey.

### CODE REVIEW

**Comment by thephez** [comment]
@QuantumExplorer @hashengineering Can you guys review this?

**Comment by thephez** [comment]
@QuantumExplorer @hashengineering Re-ping

**Comment by HashEngineering** [comment]
Sorry for missing this.  I will add these new test vectors as unit tests to `dashj` to make sure that they work.

**Review by HashEngineering — CHANGES_REQUESTED** [review]
Based on my analysis, the version bytes are incorrect in DIP14 if we want the serialization to match the human-readable formats at the end of the Serialization Format section.

Therefore, based on this, I would suggest that DCG does a separate PR to fix the mismatch between version bytes and the human-readable strings.  Then we can merge this PR.  We should check with the original author about this mismatch.

Here is my PR to add these tests into dashj: https://github.com/dashevo/dashj/pull/120 (this PR is not complete as not all requirements of DIP14 are met)

**Comment by HashEngineering** [comment]
@dashameter did you use the version bytes as defined in this DIP?  They did not work for me.

**Comment by dashameter** [comment]
> @dashameter did you use the version bytes as defined in this DIP? They did not work for me.

I did. Do they not work for you in the javascript or in the java implementation?

**Comment by HashEngineering** [comment]
> > @dashameter did you use the version bytes as defined in this DIP? They did not work for me.
> 
> I did. Do they not work for you in the javascript or in the java implementation?

The Java Implementation (dashj) as well as another tool called Bitcoin Address Utility which can convert a base58 string to a byte array. The data within the serialization of this PR matches the Java Implementation, but not the version bytes or checksum.

**Comment by dashameter** [comment]
> > > @dashameter did you use the version bytes as defined in this DIP? They did not work for me.
> > 
> > 
> > I did. Do they not work for you in the javascript or in the java implementation?
> 
> The Java Implementation (dashj) as well as another tool called Bitcoin Address Utility which can convert a base58 string to a byte array. The data within the serialization of this PR matches the Java Implementation, but not the version bytes or checksum.

@HashEngineering are you using the version bytes from this PR https://github.com/dashpay/dips/pull/81 ?

**Comment by HashEngineering** [comment]
@dashameter yes, I was using the version bytes from #81.  My comments about the incorrect version bytes were because I was looking at the  commit history of this PR rather than the DIP14 document of the master branch.  Therefore I will close out the related issue #97 and approve of this PR.

**Review by HashEngineering — APPROVED** [review]
Tested and verified the new test vectors in DashJ.

**Review by thephez — APPROVED** [review]
utACK

**Pull request merged**
