### PR TITLE
DIPs 11 (Identity) and 12 (DPNS)

### PR DESCRIPTION
**Pull request by thephez**
This PR introduces the Dash Platform Identity and DPNS DIPs

### CODE REVIEW

**Comment by thephez** [comment]
Thanks @shumkov, @antouhou, @QuantumExplorer, @cofresi, @pastapastapasta and everyone else for your hard work on these

**Review by bcarrollaz — CHANGES_REQUESTED** [review]
One reference to "DIP 5" should be "DIP0005" and one reference to "DIP 11" should be "DIP0011" in DPNS DIP Prior Work section.

**Comment by thephez** [comment]
> One reference to "DIP 5" should be "DIP0005" and one reference to "DIP 11" should be "DIP0011" in DPNS DIP Prior Work section.

Updated in https://github.com/dashpay/dips/pull/65/commits/21253e95857c6130f892c1f762cfff7e91bff2e6

**Review by bcarrollaz — APPROVED** [review]

**Review by curtcurt871 — COMMENTED** [review]
README.md

**Pull request merged**
