### PR TITLE
DIP2: increment qctx version to match current protocol

### LINKED ISSUE #119: Update DIP-2 special tx table
Upon activation of Dash Core v18's hard fork, the QcTx version will increment to `2`. Update the version number in this table once that has happened: https://github.com/dashpay/dips/blob/master/dip-0002-special-transactions.md.

### PR DESCRIPTION
**Pull request by thephez**
Dash Core v18 updated the qctx with additional field(s). See the table in https://github.com/dashpay/dips/blob/master/dip-0006.md#6-finalization-phase for details.

Closes #119

### CODE REVIEW

**Comment by thephez** [comment]
@ogabrielides @UdjinM6 @PastaPastaPasta Can someone take a look at this?

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Quorum commitment _transaction_ format/version [was not altered](https://github.com/dashpay/dash/blob/master/src/llmq/commitment.h#L137). 

It's only [`commitment`](https://github.com/dashpay/dips/blob/master/dip-0006.md#7-mining-phase) ([`qfcommit`](https://github.com/dashpay/dips/blob/master/dip-0006.md#6-finalization-phase)) [part](https://github.com/dashpay/dash/blob/master/src/llmq/commitment.h#L22-L24) of it that [was updated](https://github.com/dashpay/dash/blob/master/src/llmq/commitment.h#L28-L29).

NACK

**Comment by thephez** [comment]
> Quorum commitment _transaction_ format/version [was not altered](https://github.com/dashpay/dash/blob/master/src/llmq/commitment.h#L137).
> 
> It's only [`commitment`](https://github.com/dashpay/dips/blob/master/dip-0006.md#7-mining-phase) ([`qfcommit`](https://github.com/dashpay/dips/blob/master/dip-0006.md#6-finalization-phase)) [part](https://github.com/dashpay/dash/blob/master/src/llmq/commitment.h#L22-L24) of it that [was updated](https://github.com/dashpay/dash/blob/master/src/llmq/commitment.h#L28-L29).
> 
> NACK

Yep, I see. So we're good with [the change that was already](https://github.com/dashpay/dips/pull/110/files#diff-c9f637d5587c222734a017aa439f3db78d2befd1a4c47b71ac5e2f052e761cbd) made then?

image

**Comment by UdjinM6** [comment]
Yes, it's all good already imo.

**Pull request closed without merging**
