### PR TITLE
Readme update - convert to mediawiki and add summary table

### PR DESCRIPTION
**Pull request by thephez**
Thought this might be helpful as more DIPs are added in the future...

### CODE REVIEW

**Comment by nmarley** [comment]
Thanks for the update -- markdown is actually the preferred format for DIPs, as specified in the [README](https://github.com/dashpay/dips/commit/f5872ff49c48f207efab039d19d5d1e94516773b#diff-04c6e90faac2675aa89e2176d2eec7d8R14) and I think the README should be in this format also. Mediawiki is notoriously difficult to parse and excessively ugly (IMO).

Is there a reason that Markdown can't be used to generate the DIPs table?

**Comment by thephez** [comment]
No, there isn't.  I'd been looking at BIPs recently and just copied the format.  There are 2 options for doing it in markdown - either directly with markdown or with an HTML table in the markdown.  I'm not a big fan of either of those really, but made a quick example to show what they look like - https://raw.githubusercontent.com/thephez/dips/bde548184537751fbb4e67c3cd0adbb675d7a8ce/Table-example.md.  

I think the embedded HTML is more readable, but may not meet the markdown requirement.  Also, I inadvertently pushed the example so I'll have clean that up either way.

**Comment by nmarley** [comment]
Thanks for the examples! I think adding the table like this is the cleanest and sticks w/markdown as a bonus:

```
Number | Layer | Title | Owner | Type | Status
--- | --- | --- | --- | --- | ---
[1](dip-0001.md) | Consensus (hard fork) | Initial Scaling of the Network | Darren Tapp | Standard | Proposed
```

**Comment by thephez** [comment]
Sure. Will my last update work for you? I removed that example and switched back to markdown for the whole document.

**Comment by nmarley** [comment]
Yes, I believe that will work! Thanks!

**Pull request merged**
