### PR TITLE
Add LLMQ 100_67 to DIP6 table

### PR DESCRIPTION
**Pull request by thephez**
Related to dashpay/dash#3729

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
👍

**Comment by thephez** [comment]
Should we wait to merge this until 0.17 is released on mainnet? The quorums are already present on testnet, so I don't think that's necessary.

**Review by xdustinface — APPROVED** [review]
Looks good 👍 IMO its ok to merge already.

**Review by PastaPastaPasta — APPROVED** [review]
:+1:

**Pull request merged**
