### PR TITLE
DIP 21: LLMQ DKG Data Sharing

### PR DESCRIPTION
**Pull request by thephez**
This DIP documents changes introduced in Dash Core 0.17 that add two new P2P messages used to help masternodes recover DKG info and also support Platform features. Related Dash Core PRs are:

* [Implement P2P messages QGETDATA <-> QDATA](https://github.com/dashpay/dash/pull/3953)
* [Implement DKG data recovery / quorum verification vector
  sync](https://github.com/dashpay/dash/pull/3964)
* [Add "mode" to -llmq-qvvec-sync parameter](https://github.com/dashpay/dash/pull/4030)

Thanks to @xdustinface for documenting this change.

### CODE REVIEW

**Comment by UdjinM6** [comment]
How about https://github.com/UdjinM6/dips/commit/382f176f0bfb08d1f1aab8f56b784e018ad61f10?

**Comment by thephez** [comment]
> How about [UdjinM6@382f176](https://github.com/UdjinM6/dips/commit/382f176f0bfb08d1f1aab8f56b784e018ad61f10)?

That makes sense to me. @xdustinface Does it look good to you?

**Comment by xdustinface** [comment]
@thephez Yeah, looks good to me too 👍

**Review by UdjinM6 — APPROVED** [review]
LGTM 👍 

ACK

**Review by xdustinface — APPROVED** [review]

**Pull request merged**
