### PR TITLE
Draft DIPs 13-16 (DashPay)

### PR DESCRIPTION
**Pull request by thephez**
Introduces DashPay-related DIPs:
- [13: Identities in Hierarchical Deterministic Wallets](https://github.com/dashpay/dips/blob/feat/dashpay/dip-0013.md)
- [14: Extended Key Derivation using 256-bit Unsigned Integers](https://github.com/dashpay/dips/blob/feat/dashpay/dip-0014.md)
- [15: DashPay](https://github.com/dashpay/dips/blob/feat/dashpay/dip-0015.md)
- [16: Headers First Synchronization on Simple Payment Verification Wallets](https://github.com/dashpay/dips/blob/feat/dashpay/dip-0016.md)

Also updates [list of DIP-9 feature types](https://github.com/dashpay/dips/blob/feat/dashpay/dip-0009/assignments.md) to add new DashPay-related items.

### CODE REVIEW

**Comment by andyfreer** [comment]
Don't think we should be bundling up DIPs in PRs.  They should be individually submitted to people have the opportunity to review/comment individually.

**Comment by thephez** [comment]
This set are inter-related and reference each other so we chose to bundle as was done with DIPs 2-4 (in #9) and 6-7 (in #14).

**Comment by andyfreer** [comment]
> This set are inter-related and reference each other so we chose to bundle as was done with DIPs 2-4 (in #9) and 6-7 (in #14).
> 
> Also, this is kind of a preview for people paying attention. I wouldn't recommend doing an extensive review until the PR is changed to "Ready to Review" status. Just trying to add a bit more transparency into the process and make these things viewable prior to insta-merging like we used to.

OK thanks -  but what is the final acceptance process (meaning agreement of a specified change to the Dash protocol by stakeholders including 'Dash Core Developers' emplyed at DCG) - is it merging or setting the status to final?  This isn't clearly defined in the README.  Provided such final acceptance is setting the status to FINAL (as I think most people assume) I don't see any problem with 'insta-merging' new DIPs with a 'proposed' status. 

As the PR process itself is a good way to gain review just functionally via Github (its useful for threads like above discussing merits / issues on commits containing DIPs or sets of interrelated DIPs) my suggestion would be e.g. create a branch for status 'proposed' DIPs and use the master for status 'final' DIPs.  That way merging to master would be the point where stakeholders can accept a DIP or not in terms of an actual change to the Dash protocol that reference implementations would follow.

As a non-DCG stakeholder myself I appreciate you thinking about increasing more transparency, I also appreciate that there's not a huge amount of people outside of DCG in my position right now - but as we grow especially with the forthcoming V2 upgrade we should expect more people to want access to the DIP process especially as in Dash the governance system is the ultimate arbiter, the more transparent and open this process is, the easier its going to be to agree protocol changes at a Network level as we grow.

**Comment by andyfreer** [comment]
Unrelated to my previous comment and relating to DIP 15 content...in the abstract I think the DashPay definition should be a lot clearer.  DashPay is only an 'application' in a colloquial sense... DashPay itself refers to a Contract, which is a user-defined protocol for storing application state on the Dash Platform blockchain, owned by a private key holder (DCG).  Clients that allow access to that Contract's state are what most users would consider to be Apps and there could be many of those (DCG's reference DashPay app, a community created DashPay Webapp, etc).  This is why it's useful to use the term Dapp - the Dapp or application in this sense is a blockchain state read/written by clients implementing the DashPay protocol.  So I think it would be better to use the actuall term here and say DashPay is a Dapp on Dash consisting of the parts I mention.

**Comment by QuantumExplorer** [comment]
I thought I made that clear in the DIP, but feel free to make a PR to this when it is in in the proposed phase. I think the terminology of Dapp is more related to dips specific to platform contracts (which will come out too).

The order of these Dips is the order that they are being written, and as you can see I'm doing quite a lot of that writing, in a perfect world there would be 10 more DIPs already in a proposed status. I just can not do everything, I thought releasing this in a proposed status would be beneficial. Especially if there is a vulnerability that is discovered Andy.

So I'm guessing the first time is your issue application -> decentralized application (Dapp), is that the change you would like @andyfreer? I completely am for that change.

Just propose the changes and we will most likely accept them if they make sense.

**Comment by andyfreer** [comment]
> I thought I made that clear in the DIP, but feel free to make a PR to this when it is in in the proposed phase. I think the terminology of Dapp is more related to dips specific to platform contracts (which will come out too).

I'm just pointing out that DashPay *is* a platform contract, not an application.  Client's (e.g. DCG's DashPay Wallet) are apps (stateless clients) that provide an interface to that Contract's state which together is a Dapp on Dash.  DashPay Wallet is a Platform wallet with a stateless Dapp interface built in (DashPay), which makes it kinda unique because most Dapps aren't directly integrated with a wallet, i.e. they don't have trusted access to the Identities private key.

This is just semantics and i'm not trying to detract from your fantastic achievement here of documenting everything @QuantumExplorer... but these terms have design implications beyond the DashPay Dapp (that historically have 'confused' a lot of people) so I think it's important we clarify these which is why i'm saying it - apologies anyway, let me wait until the DIP is more developed and i'll review and comment properly.

Thanks

**Comment by QuantumExplorer** [comment]
@andyfreer the dip is pretty much good at this point, you can review it, I am just writing a blog post to accompany them and I hope that I'lll have that ready on Monday.

**Comment by QuantumExplorer** [comment]
I would wait till Monday to do PRs though.

**Comment by thephez** [comment]
> OK thanks - but what is the final acceptance process (meaning agreement of a specified change to the Dash protocol by stakeholders including 'Dash Core Developers' emplyed at DCG) - is it merging or setting the status to final? This isn't clearly defined in the README. Provided such final acceptance is setting the status to FINAL (as I think most people assume) I don't see any problem with 'insta-merging' new DIPs with a 'proposed' status.

As with BIPs, merging isn't indicative of whether or not the proposed concept will be implemented. The final acceptance is ultimately determined when an implementation is released and the network ends up upgrading or not upgrading. As assumed (correctly) by many, the status here only changes to FINAL when a proposed change becomes active on the network (i.e. the status here reflects the network rather than trying to dictate it). This is aligned with the process defined in [BIP2](https://github.com/bitcoin/bips/blob/master/bip-0002.mediawiki#specification-1).

I do still anticipate a quick turn around on PRs (there's nothing preventing adjustments after merging a proposed DIP after all). But it will be more than the 5 minutes of previous ones :slightly_smiling_face: 

> As a non-DCG stakeholder myself I appreciate you thinking about increasing more transparency, I also appreciate that there's not a huge amount of people outside of DCG in my position right now - but as we grow especially with the forthcoming V2 upgrade we should expect more people to want access to the DIP process especially as in Dash the governance system is the ultimate arbiter, the more transparent and open this process is, the easier its going to be to agree protocol changes at a Network level as we grow.

I suspect you're correct. We're trying to head in the right direction.

**Comment by andyfreer** [comment]
> > OK thanks - but what is the final acceptance process (meaning agreement of a specified change to the Dash protocol by stakeholders including 'Dash Core Developers' emplyed at DCG) - is it merging or setting the status to final? This isn't clearly defined in the README. Provided such final acceptance is setting the status to FINAL (as I think most people assume) I don't see any problem with 'insta-merging' new DIPs with a 'proposed' status.
> 
> As with BIPs, merging isn't indicative of whether or not the proposed concept will be implemented. The final acceptance is ultimately determined when an implementation is released and the network ends up upgrading or not upgrading. As assumed (correctly) by many, the status here only changes to FINAL when a proposed change becomes active on the network (i.e. the status here reflects the network rather than trying to dictate it). This is aligned with the process defined in [BIP2](https://github.com/bitcoin/bips/blob/master/bip-0002.mediawiki#specification-1).
> 
> I do still anticipate a quick turn around on PRs (there's nothing preventing adjustments after merging a proposed DIP after all). But it will be more than the 5 minutes of previous ones 
> 
> > As a non-DCG stakeholder myself I appreciate you thinking about increasing more transparency, I also appreciate that there's not a huge amount of people outside of DCG in my position right now - but as we grow especially with the forthcoming V2 upgrade we should expect more people to want access to the DIP process especially as in Dash the governance system is the ultimate arbiter, the more transparent and open this process is, the easier its going to be to agree protocol changes at a Network level as we grow.
> 
> I suspect you're correct. We're trying to head in the right direction.

I don't really agree this is aligned with BIP2.  BIPs have a draft status that allows open discussion and objections before they move to proposed - what DCG is doing is just unilaterally moving to 'proposed' stage, and as Dash has a governance system (that funds DCG) its unlikely there will be alternative implementations competing.

Essentially you seem happy that DCG can just decide changes in private and then role them out into implementations... i'm saying this isn't really going to work in the long term and its pretty centralized don't you think?

**Comment by thephez** [comment]
Note: this PR has been split into 4 separate PRs now (1 for each of the new documents).
- [13: Identities in Hierarchical Deterministic Wallets](https://github.com/dashpay/dips/pull/70)
- [14: Extended Key Derivation using 256-bit Unsigned Integers](https://github.com/dashpay/dips/pull/71)
- [15: DashPay](https://github.com/dashpay/dips/pull/72)
- [16: Headers First Synchronization on Simple Payment Verification Wallets](https://github.com/dashpay/dips/pull/73)

**Comment by thephez** [comment]
Closing as these documents are being merged in separate PRs as mentioned above.

**Pull request closed without merging**
