### PR TITLE
Update DIP-5 status to minimize potential confusion

### PR DESCRIPTION
**Pull request by thephez**
Also includes a note to clarify why the status was changed

### CODE REVIEW

**Comment by andyfreer** [comment]
I think it's important here for the public record, to point out that this DIP is being unilaterally withdrawn by DCG employees despite my objections in private including stating my opinion last Friday (5th June) that there are serious problems with the alternative planned implementation to this DIP and that I believe the Network should be given the information to decide which solution is taken here and a decision proposal raised and not a black-box decision by DCG employees.

In terms of the Dash Network, no solution has been implemented for usernames yet (within the Dash protocol / consensus) so it's inaccurate to claim that 'Not representative of the current solution to provide similar functionality'

Amongst the problems with the undocumented, non-peer reviewed & non publicly discussed alternative implementation currently only existing on the EvoNet test network are:

- Usernames, that provide the symbols used for the public keys for digital assets created and transferred by future Dash users on L2, are being removed from the blockchain to L2 itself and therefore outside of PoW consensus, giving control exclusively to Masternodes, and losing the PoW security of consensus on those names.
- Usernames are being decoupled as public key symbols to a shared hash for pubkeys called Identities so that digital assets created and transferred must be done so by hash, with usernames being relegated to aliases that allow reverse but not forward lookup (there is no way to proove which individual username an asset on L2 is created or transferred by, breaking the basic pay-by-name security / usecase of Evolution itself)
- Usernames are controlled by a contract with a private key under the control of DCG, which is under the control of Ryan Taylor, its CEO.  This means that there is the future potential for centralized control, censorship and seizure of the pubkey symbols holding user's digital property on Dash after the Evolution upgrade by DCG, compared to the trustless version described in this DIP, which would require a hard or soft fork involving consensus between miners and Masternodes to achieve.
- In the alternative planned implementation there is no known secure way to allow transfer of usernames i.e. it prevents the name market which this DIP provides.  This increases the likely hood of centralized control to resolve any name / legal disputes,

**Comment by andyfreer** [comment]
Update: Since my above comments, we now have DIPs 11 & 12 - I feel that all of my concerns are solved by those 2 DIPs.  Apart from the one issue of control of the private key for the DashPay Contract (in terms of ownership by DCG).  On that note, after some private correspondence with Ryan Taylor (DCG CEO) i'm happy this isn't a direct issue right now, so i'd like to suggest closing this PR and deprecating DIP 5 (at least I don't have any objects to do that now)

Thanks

**Review by PastaPastaPasta — APPROVED** [review]
re-utACK

**Comment by thephez** [comment]
@andyfreer Good to hear and thanks for the info :+1: Kinda funny - I was just thinking about the PR earlier in the week :slightly_smiling_face:

**Review by UdjinM6 — APPROVED** [review]

**Pull request merged**
