### PR TITLE
Remove DIP5 transaction types

### PR DESCRIPTION
**Pull request by UdjinM6**
DIP5 was withdrawn earlier via https://github.com/dashpay/dips/pull/58

### CODE REVIEW

**Review by thephez — COMMENTED** [review]
:+1: Makes sense. None of those txs were ever present on testnet/mainnet, so it's not necessary to retain them here. DIP 5 does reference those tx numbers. Maybe the "The special transaction type used for <special tx type> is <#>" sentences should be dropped from that document along with this change?

**Comment by QuantumExplorer** [comment]
👍

**Review by thephez — APPROVED** [review]
LGTM :+1:

**Review by xdustinface — APPROVED** [review]
Looks good 👍

**Pull request merged**
