### PR TITLE
Remove attemptNum from CLSIG and fix description of sig verification

### PR DESCRIPTION
**Pull request by codablock**

### CODE REVIEW

**Comment by UdjinM6** [comment]
Should also fix `Signing attempts` session I guess.

**Comment by UdjinM6** [comment]
s/session/section/ 🙈 

`Signing attempts` _section_ mentions `attemptNum` a lot and should be adjusted accordingly since we are not using it anymore.

**Comment by codablock** [comment]
The "Signing attempts" phase will still use `attemptNum`, it's just the finalization phase that didn't need it. In the finalization phase, a new signing session is started with the prevBlockHash and blockHash of the last successful attempt, but for this the `attemptNum` is not needed anymore.

**Comment by UdjinM6** [comment]
Ah, I see now. Thanks!

**Pull request merged**
